name: Unpack source

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unpack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unpack
        run: |
          test -f UABE-iOS.zip
          unzip -q UABE-iOS.zip
          rsync -a --exclude .github UABE-iOS/ ./
          rm -rf UABE-iOS UABE-iOS.zip

      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Add source"
          git push
